config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions'
  }
  

 
  devise_scope :user do
    authenticated :user do
      root 'events#index', as: :authenticated_root
    end
    get '/redirect', to: 'events#redirect', as: 'redirect'
    get '/callback', to: 'events#callback', as: 'callback'
    get '/calendars', to: 'events#calendars', as: 'calendars'
    post '/events/:calendar_id', to: 'events#new_event', as: 'new_event', calendar_id: /[^\/]+/
    resources :users
    resources :events
    # get "/events/list/all" => 'events#list'
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    resources :comments
  end 
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
     belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	 belongs_to :user
     has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	 has_many :comments
	 has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def index
        @comments = Comment.all
    end

    def new
        @user = User.find(current_user.id)
        @event = Event.find(params[:event_id])
        @comment = Comment.new
    end

    def create

        user = User.find(current_user.id)
        comment = Comment.new(comment_params)
        comment.user_id = current_user.id
        if comment.save!
            flash[:message] = 'Your comment was posted'
            redirect_to "/events/#{comment.event_id}"
        else
            flash[:message] = 'try again'
            render 'comments/'
        end
    end

    def show
        @comment = Comment.find_by_id(params[:id])
    end

    def edit
        @comment = Comment.find_by_id(params[:id])
    end

    def update
        @comment = Comment.find(params[:id])
        @event = Event.find_by_id(params[:id])
        if @comment.update(comment_params)
            flash[:message] = 'Your comment was edited'
            redirect_to "/events"
        else
            flash[:message] = 'try again'
            render "/comments/#{@comment.id}/edit"
        end
    end

    def destroy
        @event = Event.find_by_id(params[:id])
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to events_path
    end

private

def comment_params
    params.require(:comment).permit(:content, :user_id, :event_id)
end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  


  def index
    @event = Event.new
    @events = Event.all
  
  end

  def show
   @comments = Comment.all
   @comment = Comment.new  
   @event = Event.find(params[:id])
   if session[:authorization] == nil
        else
            client = Signet::OAuth2::Client.new(client_options)
            client.update!(session[:authorization])
            tokenRefresh
            service = Google::Apis::CalendarV3::CalendarService.new
            service.authorization = client
            if service.authorization.expires_at < Time.now 
            else 
                @calendar_list = service.list_calendar_lists
                @test = @calendar_list.items.first.id 
            end 

   end
  end

 
  def new
    @event = Event.new
    
  end
  def redirect
    client = Signet::OAuth2::Client.new(client_options)

    redirect_to client.authorization_uri.to_s
  end
   def callback
         client = Signet::OAuth2::Client.new(client_options)
         client.code = params[:code]
         response = client.fetch_access_token!
         
         session[:authorization] = response
         session[:authorization][:code] = params[:code]
         redirect_to "/events/#{current_user.id}"
     end 
   
    def calendars
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @calendar_list = service.list_calendar_lists
    rescue Google::Apis::AuthorizationError
    response = client.refresh!

    session[:authorization] = session[:authorization].merge(response)

    retry
  
   end 
    def events
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @event_list = service.list_events(params[:calendar_id])
  end
  def new_event
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    today = Date.today

    event = Google::Apis::CalendarV3::Event.new({
      start: Google::Apis::CalendarV3::EventDateTime.new(date: today),
      end: Google::Apis::CalendarV3::EventDateTime.new(date: today + 1),
      summary: 'New event!'
    })

    service.insert_event(params[:calendar_id], event)

    redirect_to events_url(calendar_id: params[:calendar_id])
  end


 
  def edit
  end

  
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    if @event.save
      redirect_to events_path
    else 
      render new_event_path
    end
  end

 
  def update
    respond_to do |format|
      if @event.update(event_params)
        flash[:notice] = 'Your event was created successfully.'
			redirect_to '/events'
		else
      flash[:alert] = 'Sorry, please try again.'  
			render new_event_path
      end
    end
  


  def destroy
   @comment = Comment.find(params[:id])
   @comment.destroy
        redirect_to "/comments/#{comment.post_id}"
    @event.destroy
     flash[:alert] = 'you have deleted this event.'
    
    end
  end

  private
  def client_options
    {
      client_id: Rails.application.secrets.google_client_id,
      client_secret: Rails.application.secrets.google_client_secret,
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
      redirect_uri: 'http://localhost:3000/callback'
    }
  end

    def event_params
      params.require(:event).permit(:name, :title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<h1>comments index</h1>
<% @comments.each do |c| %>
<%= c.content %>

<% end %>
<h1>COMMENT</h1>
<%= form_for Comment.new do |f| %>
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>comments show</h1>
<%= form_with(model: @comment, local: true) do |c| %>
<%=c.text_area :content%>
<%=c.hidden_field event_id, :value => @event.id %>
<%=c.submit %>
<% end %>

<% @events.comments.each do |c| %>
<%= c.content %>
<%= link_to 'Delete', "/comments/#{c.id}", method: :delete %>
<% end %>

app/views/events/index.html.erb
<h3>Event index</h3>
<h2>List of all Events:</h2>
<% @events.each do |c| %>
    <div><a href='/events/<%= c.id %>'><%= c.title %></a></div>
        <% end %>

app/views/events/list.html.erb
<h1>list of events</h1>
asdfasdfasdfasdf asdfasdfasdf
 <% @events.each do |c| %>
     <p><%= c.title %></p>
        <% end %>

app/views/events/new.html.erb
<h1>events new form</h1>

<%= form_for @event do |f| %>
  
<div>Title:<%= f.text_field :title %></div><br>
<div>Event: <%= f.text_area :content %></div><br>
	<%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h2>event show page:</h2>
<%= @event.title %>

<%= form_with(model: @comment, local: true) do |c| %>
<div>
    <div><%=c.text_area :content%></div>
     <div><%= c.hidden_field :event_id, :value => @event.id %></div>
   
    <div><%=c.submit %></div>
    <% end %>
</div>
<hr>

<br>
<% @comments.each do |c| %>
<div>
    <div><a href="<%= "/comments/#{c.id}/edit" %>"><%= c.content %></a></div>
    
    <div><%= link_to 'Delete', "/comments/#{c.id}", method: :delete %></div>
</div>

<% end %>

<%if @test != nil %>
    <%= form_tag(new_event_path(@test), method: "event", :id => "add_event") do %>
        <select id="event_id">
	        <% @calendar_list.items.each do |calendar| %>
	            <% if calendar.access_role == 'owner' %>
	                <option value="<%= calendar.id %>"><%= calendar.summary %></option>
	            <% end%>
	        <% end %>
        </select>
        <input type="hidden" name="event_id" value="<%= @event_id%>"> 
        <%= submit_tag("Add event") %>
        <% end %>
		<%= form_tag(redirect_path, method: "get") do %>             
		    <%= submit_tag "Switch Google Account" %>
		<%end%>
<% else %>	


    <%= form_tag(redirect_path, method: "get") do %>             
        <%= submit_tag "Add It to Google Calendar" %>
    <%end%> 



<%end%>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tribe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	 
<h1>TRIBE</h1>

  	 <ul class="navbar">
        <!-- <li><a href='/comments'>New comment</a></li> --> 
        <li><a href='/events'>Events</a></li>
           <!-- <li><a href='/events/list'>all events</a></li> -->
        <li class=><%= link_to "Log In", '/'%></li>
        <li class=><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <li class=><%= link_to "Settings",  edit_user_registration_path %></li>
       
      </ul>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>